apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yugabyte-test

resources:
  - namespace.yaml
  - strimzi/kafka-cluster.yaml
  - strimzi/kafka-connect.yaml
  - prometheus/prometheus.yaml
  - producer/producer.yaml
