apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yugabyte-test

resources:
  - namespace.yaml
  - hammerdb/configmap.yaml
  - hammerdb/deployment.yaml
  - sysbench/configmap.yaml
  - sysbench/deployment.yaml
  - prometheus/prometheus.yaml
